# Generated by Django 4.2.14 on 2024-07-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plants',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='plants',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
