# Generated by Django 4.2.14 on 2024-07-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0003_alter_plants_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plants',
            name='category',
            field=models.CharField(max_length=15),
        ),
    ]
