# Generated by Django 4.2.14 on 2024-07-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0004_alter_plants_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plants',
            name='category',
            field=models.CharField(choices=[('1', 'Fruit'), ('2', 'Vegetables'), ('3', 'Decorating tree'), ('4', 'Medicine')], max_length=1),
        ),
    ]
