# Generated by Django 4.2.14 on 2024-07-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0005_alter_plants_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plants',
            name='is_edible',
            field=models.BooleanField(default=False),
        ),
    ]
