# Generated by Django 5.0.6 on 2024-07-23 02:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("about", models.TextField()),
                ("used_for", models.TextField()),
                ("plant_image", models.ImageField(upload_to="plants/")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Succulents", "Succulents"),
                            ("Cacti", "Cacti"),
                            ("Flowering Plants", "Flowering Plants"),
                            ("Herbs", "Herbs"),
                            ("Shrubs", "Shrubs"),
                            ("Trees", "Trees"),
                            ("Vines and Climbers", "Vines and Climbers"),
                            ("Ferns", "Ferns"),
                            ("Grasses", "Grasses"),
                            ("Aquatic Plants", "Aquatic Plants"),
                            ("Bulbs", "Bulbs"),
                            ("Ornamental Plants", "Ornamental Plants"),
                        ],
                        default="Succulents",
                        max_length=50,
                    ),
                ),
                ("is_edible", models.BooleanField(default=False)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
