# Generated by Django 5.0.7 on 2024-07-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
