# Generated by Django 5.0.7 on 2024-07-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plants',
            name='category',
            field=models.CharField(choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor'), ('Fruit', 'Fruit'), ('Vegetable', 'Vegetable'), ('Herb', 'Herb'), ('Flower', 'Flower'), ('Tree', 'Tree'), ('Shrub', 'Shrub')], max_length=255),
        ),
    ]
