# Generated by Django 5.0.7 on 2024-07-23 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='category',
            field=models.CharField(choices=[('Vegetable', 'Vegetable'), ('Fruit', 'Fruit'), ('Tree', 'Tree')], max_length=100),
        ),
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='is_edible',
            field=models.BooleanField(),
        ),
    ]
