# Generated by Django 5.0.7 on 2024-07-21 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Plants', '0002_alter_plants_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
