# Generated by Django 5.0.7 on 2024-07-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plants', '0005_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
    ]
