# Generated by Django 5.0.7 on 2024-07-24 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plants', '0006_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='plants',
            name='categorys',
            field=models.ManyToManyField(to='Plants.relationship'),
        ),
    ]
