# Generated by Django 5.0.7 on 2024-07-24 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Plants', '0007_plants_categorys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plants',
            name='rating',
        ),
    ]
