# Generated by Django 5.0.7 on 2024-07-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plants', '0008_remove_plants_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plants',
            name='categorys',
        ),
        migrations.AlterModelOptions(
            name='plants',
            options={'verbose_name_plural': 'Plants'},
        ),
        migrations.AddField(
            model_name='plants',
            name='rating',
            field=models.SmallIntegerField(choices=[(1, 'One Star'), (2, 'Two Star'), (3, 'Three Star'), (4, 'Four Star'), (5, 'Five Star')], default=3),
        ),
        migrations.DeleteModel(
            name='Relationship',
        ),
    ]
