# Generated by Django 5.0.7 on 2024-07-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plants", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plant",
            name="category",
            field=models.CharField(
                choices=[
                    ("fruit", "Fruit"),
                    ("tree", "Tree"),
                    ("vegetables", "Vegetables"),
                ],
                max_length=100,
            ),
        ),
    ]
