# Generated by Django 4.2.13 on 2024-07-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=1024)),
                ("last_name", models.CharField(max_length=1024)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Plant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
                ("about", models.TextField()),
                ("used_for", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Tree", "Tree"),
                            ("Fruit", "Fruit"),
                            ("Vegetables", "Vegetables"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_edible", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
