# Generated by Django 4.2.13 on 2024-07-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plant",
            name="image",
            field=models.ImageField(default=None, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="plant",
            name="category",
            field=models.CharField(
                choices=[
                    ("Tree", "Tree"),
                    ("Fruit", "Fruit"),
                    ("Vegetables", "Vegtables"),
                ],
                max_length=50,
            ),
        ),
    ]
