# Generated by Django 4.2.13 on 2024-07-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_plant_image_alter_plant_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plant",
            name="image",
            field=models.ImageField(
                default="https://images.pexels.com/photos/1128678/pexels-photo-1128678.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
                upload_to="images/",
            ),
        ),
    ]
