# Generated by Django 4.2.13 on 2024-07-24 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_plant_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plant",
            name="image",
            field=models.ImageField(
                default="images/default_fruit.jpg", upload_to="images/"
            ),
        ),
        migrations.CreateModel(
            name="Reivew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("message", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.plant"
                    ),
                ),
            ],
        ),
    ]
