# Generated by Django 4.2.13 on 2024-07-24 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_plant_image_reivew"),
    ]

    operations = [
        migrations.CreateModel(
            name="Countries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="plant",
            name="countries",
            field=models.ManyToManyField(to="main.countries"),
        ),
    ]
