# Generated by Django 5.0.7 on 2024-07-22 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PagesPlanteer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='categore',
            new_name='category',
        ),
    ]
