# Generated by Django 5.0.7 on 2024-07-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PagesPlanteer', '0003_alter_plant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='created_at',
            field=models.DateField(),
        ),
    ]
